/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "depositar_retirar_banco.h"

bool_t
xdr_depositar_argumentos (XDR *xdrs, depositar_argumentos *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->cantidadTransaccion))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->cantidadCuenta))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_retirar_argumentos (XDR *xdrs, retirar_argumentos *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->cantidadTransaccion))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->cantidadCuenta))
		 return FALSE;
	return TRUE;
}
