/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DEPOSITAR_RETIRAR_BANCO_H_RPCGEN
#define _DEPOSITAR_RETIRAR_BANCO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct depositar_argumentos {
	double cantidadTransaccion;
	double cantidadCuenta;
};
typedef struct depositar_argumentos depositar_argumentos;

struct retirar_argumentos {
	double cantidadTransaccion;
	double cantidadCuenta;
};
typedef struct retirar_argumentos retirar_argumentos;

#define DEPOSITAR_RETIRAR_BANCO 0x20000001
#define VERSION_DEPOSITAR_RETIRAR_BANCO 1

#if defined(__STDC__) || defined(__cplusplus)
#define depositar 1
extern  double * depositar_1(depositar_argumentos *, CLIENT *);
extern  double * depositar_1_svc(depositar_argumentos *, struct svc_req *);
#define retirar 2
extern  double * retirar_1(retirar_argumentos *, CLIENT *);
extern  double * retirar_1_svc(retirar_argumentos *, struct svc_req *);
extern int depositar_retirar_banco_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define depositar 1
extern  double * depositar_1();
extern  double * depositar_1_svc();
#define retirar 2
extern  double * retirar_1();
extern  double * retirar_1_svc();
extern int depositar_retirar_banco_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_depositar_argumentos (XDR *, depositar_argumentos*);
extern  bool_t xdr_retirar_argumentos (XDR *, retirar_argumentos*);

#else /* K&R C */
extern bool_t xdr_depositar_argumentos ();
extern bool_t xdr_retirar_argumentos ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DEPOSITAR_RETIRAR_BANCO_H_RPCGEN */
